### ISSUE TITLE
Adding an Application Subtopic?

### ISSUE THREAD

**Issue by KafkaNoNeko** [open-resources/learning_outcomes#10]
I've noticed that there are quite a few application LOs in Volume 2.  Should a subtopic on the application of the concepts be added for each topic?

See:

- Volume 1, Sections 17.4,17.5,17.6, 17.8
- Volume 2, Sections 9.2, 10.5, 10.6, 11.7, 13.6, 13.7

**Comment by SteveCollins17** [comment]
I don't think we need an applications subtopic for each topic but maybe under Physics in General we can add a catch all LO like "Apply physical principles to real world application". What do you think?

**Comment by KafkaNoNeko** [comment]
Yeah, that sounds good!  What do you suggest we do with these LOs listed above?  Should they be ignored or should they be added to the topic outcome of their respective topics?

**Comment by SteveCollins17** [comment]
For sure those LOs should be added to the topic outcome of their respective topics. I will add the "Apply physical principles to real world application" LO to Physics in General
