### ISSUE TITLE
Biot-Savart Law Subtopic Title

### ISSUE THREAD

**Issue by maya-patel** [open-resources/learning_outcomes#11]
There is a subtopic called "Magnetic Force on Current-Carrying Wires(Biot-Savart Law)" but I think that this should just be called "Magnetic Force on Current-Carrying Wires" and then "Magnetic Field Produced by Electrical Currents(Ampere's Law)" should be called "Magnetic Field Produced by Electrical Currents(Ampere's Law and Biot-Savart Law)". I know that's quite long but Biot-Savart Law is about magnetic field, not magnetic force. And Ampere's law and Biot-Savart law really go hand in hand, Ampere's law is really just a specific case of Biot-Savart.

**Comment by SteveCollins17** [comment]
Yes I completely agree! I will make that change right now
