### ISSUE TITLE
LC Circuits Subtopic

### ISSUE THREAD

**Issue by maya-patel** [open-resources/learning_outcomes#12]
I think we should add an LC circuits subtopic, there's an RL and RLC one so it's hard to place the LC circuit LOs without a specific spot for them too.

**Comment by maya-patel** [comment]
We could also just add them under the RLC circuits topic, though. What do you think @SteveCollins17 ?

**Comment by SteveCollins17** [comment]
Yes that totally make sense to have a LC subtopic. I will add that right now
