### ISSUE TITLE
Momentum LOs

### ISSUE THREAD

**Issue by maya-patel** [open-resources/learning_outcomes#14]
The Momentum LOs seem to be lacking when it comes to collisions. This question is an example of one that should have more relevant LOs : https://github.com/open-resources/instructor_physics_bank/pull/134

**Comment by maya-patel** [comment]
This one too! https://github.com/open-resources/instructor_physics_bank/pull/135

**Comment by maya-patel** [comment]
"Use conservation of momentum and conservation of mechanical energy to solve an elastic collision problem." , "Use conservation of momentum to solve an elastic collision problem."

**Comment by SteveCollins17** [comment]
Ya there aren't that many LOs for momentum I agree. @maya-patel for sure add those 2 suggested LOs and I will try and think of a few more to fill in the gaps

**Comment by SteveCollins17** [comment]
ok added those 2 LOs and a catch all "Use conservation of momentum to solve a problem." let me know if any other questions fall through the cracks
