### ISSUE TITLE
Spring LOs

### ISSUE THREAD

**Issue by maya-patel** [open-resources/learning_outcomes#15]
There are no spring LOs under the Force topic, so nothing about hookes law. See https://github.com/open-resources/instructor_physics_bank/pull/153

**Comment by maya-patel** [comment]
From the textbook LOs Firas sent: "Use Hooke's law to relate the force exerted by a stretched spring to the displacement from equilibrium and the spring constant."

**Comment by maya-patel** [comment]
"Use the spring potential energy equation to solve for an unknown quantity."

**Comment by KafkaNoNeko** [comment]
There are also no spring LOs for the 2012 Final Q8 (Identical Mass-Springs with Different Displacement).

**Comment by SteveCollins17** [comment]
ok I've added a few LOs for springs. I think 6.11.2.2 - "Use Hooke's Law to determine the force, displacement from equilibrium, or spring constant of a system" works for both questions. The LO is pretty much identical to the one from the textbook just a little more general.
