### ISSUE TITLE
Momentum and Net Force

### ISSUE THREAD

**Issue by maya-patel** [open-resources/learning_outcomes#16]
I think these could both use an Lo that is more specific about the relationship between momentum and force. This one sort of fits but it would need to be added: "Relate the impulse delivered to an object to the average applied force and duration of the force."

**Comment by maya-patel** [comment]
https://github.com/open-resources/instructor_physics_bank/pull/177/files

**Comment by maya-patel** [comment]
https://github.com/open-resources/instructor_physics_bank/pull/130/files

**Comment by SteveCollins17** [comment]
ok I've added that LO under Impulse. I've also added 7.2.1.5 - "Relate momentum to force." and 7.2.1.6 - "Determine the net force on an object from the momentum as a function of time" which I think can both applied to both questions
