### ISSUE TITLE
Kinetic Energy of a Simple Pendulum System

### ISSUE THREAD

**Issue by KafkaNoNeko** [open-resources/learning_outcomes#22]
See https://github.com/open-resources/instructor_physics_bank/pull/353#issuecomment-890408558

**Comment by SteveCollins17** [comment]
I've added LO 8.2.5 - "Calculate the kinetic energy of a simple pendulum." which should be good for the question.

**Comment by SteveCollins17** [comment]
as well as LO 8.3.2.5 - " Calculate the gravitational potential energy of a simple pendulum."

**Comment by KafkaNoNeko** [comment]
> Calculate the gravitational potential energy of a simple pendulum.

I'm not sure why this is not showing up in the .csv list but it's there in the yml file

**Comment by SteveCollins17** [comment]
> > Calculate the gravitational potential energy of a simple pendulum.
> 
> I'm not sure why this is not showing up in the .csv list but it's there in the yml file

hmmm I'll double check the syntax and indentation but besides that im not sure

**Comment by SteveCollins17** [comment]
ah there seems to be 2 potential energy subtopics. I will remove one of them, hopefully this doesn't mess up too many things. Should only effect the conservation of energy subtopic.

**Comment by KafkaNoNeko** [comment]
Thanks, I see it now!
