### ISSUE TITLE
Inertia and Momentum

### ISSUE THREAD

**Issue by KafkaNoNeko** [open-resources/learning_outcomes#23]
See https://github.com/open-resources/instructor_physics_bank/pull/279#issuecomment-890426207

**Comment by SteveCollins17** [comment]
This ones a little tricky but really all you need is to know that inertia is an objects resistance to motion i.e. its mass, along with p=mv and Ek=1/2mv^2, then solve a system of 2 equations. So I'd use LOs 6.4.3 - " define inertia", 7.2.1.7 - "Define momentum", 8.2.6 - "define kinetic energy", and 1.11.3.1 - "Solve a system of 2 equations"

**Comment by KafkaNoNeko** [comment]
I see! Thank you!!
