### ISSUE TITLE
Velocity and Acceleration

### ISSUE THREAD

**Issue by KafkaNoNeko** [open-resources/learning_outcomes#25]
Please see https://github.com/open-resources/instructor_physics_bank/pull/322#issuecomment-904954765

**Comment by SteveCollins17** [comment]
ok for this one you need to know to use d=1/2at^2 and proportional reasoning, so i think LO 4.1.2 - "Identify which equations of motion are to be used to solve for unknowns." along with the new LO I've also added, LO 1.1.1 - "Use proportional reasoning" would be good for this question

**Comment by KafkaNoNeko** [comment]
Thanks!!
