### ISSUE TITLE
Create new subtopic called "Diagnostic" under the "Math" Topic

### ISSUE THREAD

**Issue by firasm** [open-resources/learning_outcomes#26]
Hey @SteveCollins17 and @KafkaNoNeko it's been a long time since I've done this and I don't want to do it wrong...with the scripts. I feel like some basic instructions/documntation would also be nice!

Could one of you please create a new subtopic called "Diagnostic" under the "Math" Topic?

Thanks!

Firas

**Comment by SteveCollins17** [comment]
Yup I will add that subtopic right away and start putting together a quick instruction document explaining the LOs, numbering format, to put new additions at the bottom of the list, etc.. Do you just want that as comments at the top of the MasterList yml?

**Comment by firasm** [comment]
I think a couple of short instructions can just be added to this README file: https://github.com/open-resources/learning_outcomes/blob/main/README.md

**Comment by SteveCollins17** [comment]
Hey @KafkaNoNeko do you want to take a look at what I've added to the README file and see if I've missed anything or if there is something you would like to add.

**Comment by KafkaNoNeko** [comment]
> 
> 
> Hey @KafkaNoNeko do you want to take a look at what I've added to the README file and see if I've missed anything or if there is something you would like to add.

It looks good in general!  The only issue is 

```
If a specific subtopic does not have a subsubtopic the tagging format simply reduces to the format (Topic.Subtopic.LearningOutcome) leaving a tag with only 3 values. (Ex. 2.4.2)
```

It seems this is not the case in the csv file.  For example, the math topic outcomes are numbered 1.1.1.0 and 1.1.1.1 instead of 1.1.1. and 1.1.2.

**Comment by SteveCollins17** [comment]
Right ok will change that. Thanks!
