### ISSUE TITLE
Add two topics

### ISSUE THREAD

**Issue by firasm** [open-resources/learning_outcomes#27]
Dr. Peyman Yousefi from APSC 181 has requested the addition of two subtopics in the kinematics topic:

Kinematics:
- Constrained Motion of Connected Particles: 
- Analyze a system of connected particles to solve for the velocity and acceleration of one of the particles.

Let's add these two to the LOs.

**Comment by KafkaNoNeko** [comment]
@SteveCollins17 I am not too sure where to add these (and I am afraid of breaking the ordering).  Could you do it instead please?

**Comment by SteveCollins17** [comment]
yup I've added the subtopic "Constrained Motion of Connected Particles:" with the LO "Analyze a system of connected particles to solve for the velocity and acceleration of one of the particles." to the Kinematics(2D and 3D) Topic.
