### ISSUE TITLE
Calculating mass

### ISSUE THREAD

**Issue by KafkaNoNeko** [open-resources/learning_outcomes#28]
Please see [this](https://github.com/open-resources/instructor_physics_bank/pull/274#discussion_r666682268).

**Comment by SteveCollins17** [comment]
ok so I would say that part a and b are just freebie steps to lead you in the right direction toward getting the values needed to calculate the center of mass of the system so LO 10.4.1.1 - "Calculate the center of mass of a given system.{324},10.4.1.1" is good for this question.

**Comment by KafkaNoNeko** [comment]
Thank you!!
