### ISSUE TITLE
Missing topics regarding quantum mechanics/ wave optics

### ISSUE THREAD

**Issue by Tarek-Alkabbani** [open-resources/learning_outcomes#30]
Phys 122, 2018 final q5 has a question covering topics relating to de Broglie and matter waves. It utilizes de Broglie's equation. We currently don't have any topics relating to quantum mechanics, this type of question could be inserted into the wave topics if we add the appropriate learning outcomes but I think that we should have a proper section for quantum mechanics for future proofing. 

Link to branch: https://github.com/open-resources/instructor_physics_bank/pull/919 

Question: 
![image](https://user-images.githubusercontent.com/97619957/173893470-1229e4f2-31e3-44a5-a152-b6f59fed8362.png)

**Comment by firasm** [comment]
@Tarek-Alkabbani:

Thanks for your patience, these LOs have now been added in #43 :

```
    Light:
        - Identify to the concept of diffraction in relation to microscopy.
        - Explore how waves bend or spread when passing through apertures or obstacles
        - Utilize principles such as wavelength of light, mass of electrons and neutrons, Planck's constant, and particle speed.
```
