### ISSUE TITLE
New topic: Light

### ISSUE THREAD

**Issue by maya-patel** [open-resources/learning_outcomes#32]
I think we could add a new topic with learning outcomes from chapters 25, 26 and 27 of the OpenStax textbook. Specifically for this tutorial: https://github.com/open-resources/private_question_sources/blob/main/2022%20Summer/122-John/Tutorial03/GPSV_2020_Phys122PrairieLearn.pdf

**Comment by maya-patel** [comment]
https://github.com/open-resources/instructor_physics_bank/pull/1051

**Comment by firasm** [comment]
Hi @husnaeva - are you able to take care of this ?

**Comment by husnaeva** [comment]
> Hi @husnaeva - are you able to take care of this ?

yes!

**Comment by husnaeva** [comment]
> I think we could add a new topic with learning outcomes from chapters 25, 26 and 27 of the OpenStax textbook. Specifically for this tutorial: https://github.com/open-resources/private_question_sources/blob/main/2022%20Summer/122-John/Tutorial03/GPSV_2020_Phys122PrairieLearn.pdf

@maya-patel i can't seem to find chapters 25-27 in the textbook, are your referring to the chapters in Volume 3? https://openstax.org/details/books/university-physics-volume-3

**Comment by maya-patel** [comment]
> @maya-patel i can't seem to find chapters 25-27 in the textbook, are your referring to the chapters in Volume 3? https://openstax.org/details/books/university-physics-volume-3

Sorry, I was accidentally looking at the American version! Yes, there will be some in Volume 3 that will work.
