### ISSUE TITLE
Redundant subtopics?

### ISSUE THREAD

**Issue by KafkaNoNeko** [open-resources/learning_outcomes#4]
There are some topics and subtopics with the same title in the yaml document.  I believe this could lead to confusion later on. Should these subtopics be kept?

![image](https://user-images.githubusercontent.com/45921274/119238384-f8927100-baf6-11eb-91f5-f60ef76346de.png)

This happens for vectors and work.

**Comment by SteveCollins17** [comment]
Hi @KafkaNoNeko I thought I had gone through and made sure that wouldn't happen but I guess I missed a few. Just delete the redundant subtopic and put any relevant LOs under the topic.
