### ISSUE TITLE
LOs which seem to fit better in a general physics context

### ISSUE THREAD

**Issue by KafkaNoNeko** [open-resources/learning_outcomes#5]
I am not too sure where to place the LOs from:

- Section 1.1 (LOs 1.1.1 and 1.1.4)
- Section 1.2
- Section 1.7

since it feels that they would fit better in a general physics context.

**Comment by SteveCollins17** [comment]
Ok yes I agree they fit in a topic of general physics. I put a Topic in between Math and Vectors named Physics in General with subtopics of Units and Solving Problems, hopefully those LOs will fit in somewhere there.
