### ISSUE TITLE
Section 4.5 - Relative Motion in One and Two Dimensions

### ISSUE THREAD

**Issue by KafkaNoNeko** [open-resources/learning_outcomes#6]
There does not seem to be a subtopic for relative motion and I am not sure where to place the LOs in section 4.5.

**Comment by SteveCollins17** [comment]
I've created a new subtopic under Kinematics(2D and 3D) for Relative Motion. I don't think a Relative Motion subtopic is necessary under Kinematics (1D) but if it is needed just add one there as well.
