### ISSUE TITLE
Topic and subtopic LOs

### ISSUE THREAD

**Issue by KafkaNoNeko** [open-resources/learning_outcomes#7]
In general, I have finished populating the yaml file with learning outcomes but I had issues deciding where to place some of them.  Most of the LOs fit pretty well under sub-topics and this resulted in some topics having 'no' learning outcome.  Having one LO appear twice - once in the topic section and once in the subtopic section - feels redundant and I am unsure how to approach this.

I would appreciate it if someone could go over the work and provide some feedback!

**Comment by firasm** [comment]
Hi @KafkaNoNeko, I agree it's a bit redundant to have some of the LOs appear in the Topic section, however it may be something we have to do. 

One other option is to write some learning outcomes ourselves (that don't exist in the book).

@SteveCollins17 can you have a look and let us know your thoughts?

**Comment by SteveCollins17** [comment]
I see Topic LOs as very general and at a high level or encompassing the entire Topic, most of the LOs from the text are rather specific so it does not surprise me that some Topics went without any LOs. I think using a LO twice in both the Topic and Subtopic is redundant and should be avoided. Determining which one to pick will be on a case by case basis. However, I see a few LOs that are used in both the corresponding physics topic/subtopic as well as the corresponding math topic/subtopic, which I think is the correct way to do it as for example LO{101} "Find instantaneous acceleration at a specified time on a graph of velocity versus time.". This LO should be under both Graphs and Acceleration/Instantaneous I think. 

The LOs look great! I've made just a couple small changes but for the most part they are where I would put them

**Comment by SteveCollins17** [comment]
I think writing our own LOs would be beneficial but time consuming. It might be best to wait for questions that don't have a specific LO that applies to them to identify the areas that need our own LOs.

**Comment by firasm** [comment]
Okay let's consider this resolved then. Will look at filling in some LOs later
