### ISSUE TITLE
Dissipative processes

### ISSUE THREAD

**Issue by maya-patel** [open-resources/learning_outcomes#9]
This pull requests outlines a question about dissipative processes. I don't think any of the current energy LOs really cover the concept of dissipation so we could add one about dissipative processes or something more general about understanding energy in terms of thermodynamics, outside of bernoulli's principle.

https://github.com/open-resources/instructor_physics_bank/pull/38

**Comment by SteveCollins17** [comment]
ok I've added LO 17.1.8 - "Define a dissipative process." which I think works for the question
